In [1]:
import pandas as pd
from datetime import datetime

In [2]:
df = pd.read_csv('bank_transactions.csv')

In [3]:
df.head()

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,T3,C4417068,26/11/96,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,T4,C5342380,14/9/73,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,T5,C9031234,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048567 entries, 0 to 1048566
Data columns (total 9 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   TransactionID            1048567 non-null  object
 1   CustomerID               1048567 non-null  object
 2   CustomerDOB              1045170 non-null  object
 3   CustGender               1047467 non-null  object
 4   CustLocation             1048416 non-null  object
 5   CustAccountBalance       1046198 non-null  float64
 6   TransactionDate          1048567 non-null  object
 7   TransactionTime          1048567 non-null  int64
 8   TransactionAmount (INR)  1048567 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 72.0+ MB

In [5]:
df.describe(include='all')

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
count,1048567,1048567,1045170,1047467,1048416,1.046198e+06,1048567,1.048567e+06,1.048567e+06
unique,1048567,884265,17254,3,9355,NaN,55,NaN,NaN
top,T1,C5533885,1/1/1800,M,MUMBAI,NaN,7/8/16,NaN,NaN
freq,1,6,57339,765530,103595,NaN,27261,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,1.154035e+05,NaN,1.570875e+05,1.574335e+03
std,NaN,NaN,NaN,NaN,NaN,8.464854e+05,NaN,5.126185e+04,6.574743e+03
min,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0.000000e+00,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,4.721760e+03,NaN,1.240300e+05,1.610000e+02
50%,NaN,NaN,NaN,NaN,NaN,1.679218e+04,NaN,1.642260e+05,4.590300e+02
75%,NaN,NaN,NaN,NaN,NaN,5.765736e+04,NaN,2.000100e+05,1.200000e+03
max,NaN,NaN,NaN,NaN,NaN,1.150355e+08,NaN,2.359590e+05,1.560035e+06

In [6]:
df.isnull().sum()

TransactionID                 0
CustomerID                    0
CustomerDOB                3397
CustGender                 1100
CustLocation                151
CustAccountBalance         2369
TransactionDate               0
TransactionTime               0
TransactionAmount (INR)       0
dtype: int64

In [7]:
df['CustLocation'] = df['CustLocation'].fillna('Not available')

In [8]:
df['CustomerDOB'] = df['CustomerDOB'].fillna(1/1/2008)

In [9]:
df['CustGender'] = df['CustGender'].fillna(df['CustGender'].mode()[0])

In [10]:
df['CustAccountBalance']=df['CustAccountBalance'].fillna(0)

In [11]:
df.isnull().sum()

TransactionID              0
CustomerID                 0
CustomerDOB                0
CustGender                 0
CustLocation               0
CustAccountBalance         0
TransactionDate            0
TransactionTime            0
TransactionAmount (INR)    0
dtype: int64

In [12]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'transactionamount_(inr)':'transaction_amount'})

In [13]:
df.columns

Index(['transactionid', 'customerid', 'customerdob', 'custgender',
       'custlocation', 'custaccountbalance', 'transactiondate',
       'transactiontime', 'transaction_amount'],
      dtype='object')

In [14]:
#convert the customerdob to datetime format  1/1/2005 se  2005-01-10
df['customerdob']=pd.to_datetime(df['customerdob'],format='%d/%m/%y', errors='coerce')

In [15]:
#create a age columns extracting the age from the customerdob column  EXAMPLE 9/1/2005 se  2005-01-10 se 2024-06-01 se age 19
today = datetime.today()
df['age'] = (today - df['customerdob']).dt.days // 365

In [16]:
#create a age columns 
labels = ['young','middle_aged','old']
df['age_groups'] = pd.qcut(df['age'], q=3, labels=labels)

In [17]:
df[['age_groups', 'age']].head()

    age_groups   age
0        young  32.0
1        young -31.0
2        young  29.0
3          old  52.0
4  middle_aged  38.0

In [18]:
# time feature 
df['transactiondate'] = pd.to_datetime(df['transactiondate'],format='%d/%m/%y', errors='coerce')
df['month'] = df['transactiondate'].dt.month
df['day']= df['transactiondate'].dt.day

In [19]:
df

,transactionid,customerid,customerdob,custgender,custlocation,custaccountbalance,transactiondate,transactiontime,transaction_amount,age,age_groups,month,day
0,T1,C5841053,1994-01-10,F,JAMSHEDPUR,17819.05,2016-08-02,143207,25.0,32.0,young,8,2
1,T2,C2142763,2057-04-04,M,JHAJJAR,2270.69,2016-08-02,141858,27999.0,-31.0,young,8,2
2,T3,C4417068,1996-11-26,F,MUMBAI,17874.44,2016-08-02,142712,459.0,29.0,young,8,2
3,T4,C5342380,1973-09-14,F,MUMBAI,866503.21,2016-08-02,142714,2060.0,52.0,old,8,2
4,T5,C9031234,1988-03-24,F,NAVI MUMBAI,6714.43,2016-08-02,181156,1762.5,38.0,middle_aged,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048562,T1048563,C8020229,1990-04-08,M,NEW DELHI,7635.19,2016-09-18,184824,799.0,36.0,middle_aged,9,18
1048563,T1048564,C6459278,1992-02-20,M,NASHIK,27311.42,2016-09-18,183734,460.0,34.0,young,9,18
1048564,T1048565,C6412354,1989-05-18,M,HYDERABAD,221757.06,2016-09-18,183313,770.0,36.0,middle_aged,9,18
1048565,T1048566,C6420483,1978-08-30,M,VISAKHAPATNAM,10117.87,2016-09-18,184706,1000.0,47.0,old,9,18
1048566,T1048567,C8337524,1984-03-05,M,PUNE,75734.42,2016-09-18,181222,1166.0,42.0,old,9,18

In [20]:
from sqlalchemy import create_engine
import psycopg2

In [21]:
conn = psycopg2.connect(
    host = 'localhost', 
    database = 'bank_transaction',
    user = 'postgres',
    password = '1234',
    port = '5432'
)
print("connect successfully")
conn.close()

connect successfully

In [22]:
engine = create_engine(f"postgresql+psycopg2://postgres:1234@localhost:5432/bank_transaction")
table_name = 'customer_transactions'
df.to_sql(table_name, engine, if_exists='replace', index=False) 
print("DataFrame has been written to the PostgreSQL database successfully.")

DataFrame has been written to the PostgreSQL database successfully.